### ISSUE TITLE
Need parallel version

### ISSUE THREAD

**Issue by kwalcock** [clulab/fatdynet#15]
For at least Linux it would be very useful to have a version compiled for GPU.

I wonder whether the best strategy would be to create a branch and then to replace in that branch only the Linux *.so compiled file.  The other two compiled files could be removed to prevent accidents.

The disadvantage is that someone would need to publishLocal in order to use it.

**Comment by MihaiSurdeanu** [comment]
+1!

**Comment by kwalcock** [comment]
There is a branch kwalcock-cude for this.  Marco was notified.
